config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborators
  end
  resources :charges, only: [:new, :create]
  resources :downgrade, only: [:new, :create]
  post 'downgrade/create'
  
  get 'about' => 'welcome#about'

  root 'welcome#index'
  
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
    belongs_to :user
    belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable 
  has_many :wikis, dependent: :destroy
  has_many :collaborators
  has_many :collaborated_wikis, through: :collaborators, source: :wiki

  after_initialize :initialize_role
  
  enum role: [:standard, :premium, :admin]
  
  private
  
  def initialize_role
    self.role ||= :standard
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :collaborator_users, through: :collaborators, source: :user

  after_initialize :initialize_role
  
  private
  
  def initialize_role
    self.private = false if self.private.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_in) do |user_params|
        user_params.permit(:username, :email)
      end
    end
end   

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
     
   customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
  )

 
  charge = Stripe::Charge.create(
    customer: customer.id, # Note -- this is NOT the user_id in your app
    amount: 15_00,
    description: "BigMoney Membership - #{current_user.email}",
    currency: 'usd'
  )
  
  current_user.premium!

  flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."

  redirect_to root_path
  
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: 15_00
    }
  end

end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
  def new
  end

  def create
    current_user.update_attribute(:role, 0)
    wikis = Wiki.all
    wikis.each do |wiki|
      if wiki.user.id == current_user.id
        wiki.update_attribute(:private, false)
      end
    end
  
    flash[:notice] = "You have successfully downgraded your account."
    
    redirect_to root_path
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    if current_user.present?
      #collaborators = []
      #@wiki.collaborators.each do |collaborator|
        #collaborators << collaborator.email
      #end
      unless (@wiki.private == false) || @wiki.user == current_user || collaborators.include?(current_user.email) || current_user.admin?
        flash[:alert] = "You are not authorized to view this wiki."
        redirect_to new_charge_path
      end
    else
      flash[:alert] = "You are not authorized to view this wiki."
      redirect_to new_user_registration_path
    end
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user
    authorize @wiki
    emails = params[:wiki][:add_collaborator].split(',').map(&:strip)
    @wiki.collaborator_users = User.where(email: emails)
    
    if @wiki.save
      flash[:notice] = "Your wiki was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your wiki. Please try again later."
      render :new
    end
  end

  def update 
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    authorize @wiki
    emails = params[:wiki][:add_collaborator].split(',').map(&:strip)
    @wiki.collaborator_users = User.where(email: emails)

    if @wiki.save && (@wiki.user == current_user || current_user.admin?)
     
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    elsif @wiki.save
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        options = {
          filter_html:     true,
          hard_wrap:       true,
          link_attributes: { rel: 'nofollow', target: "_blank" },
          space_after_headers: true,
          fenced_code_blocks: true
        }
    
        extensions = {
          autolink:           true,
          superscript:        true,
          disable_indented_code_blocks: true
        }
    
        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)
    
        markdown.render(text).html_safe
      end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    def user_is_authorized_to_create?
        current_user && (current_user.admin? || current_user.premium?)
    end
    
    def user_is_authorized_to_update?
        current_user
    end
    
    def user_is_authorized_to_delete?
        current_user && (current_user == @wiki.user || current_user.admin?)
    end

    def show_collaborators
        @wiki.collaborator_users.collect{|user| user.email}.join(', ')
    end
    

end

app/views/charges/create.html.erb
<h1>Charge#create</h1>
<p>Find me in app/views/charge/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <h4>Click the button!</h4>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% end %>

app/views/collaborators/_form.html.erb
 <div class="form-group">
        <div class="col-md-8">
                <%= form_for @wiki do |f| %>
                <div class="form-group">
                        <%= f.label :add_collaborator%>
                        <%= f.text_field :add_collaborator,
                                class: 'form-control',
                                placeholder: "Enter collaborator emails (separated by commas)",
                                value: @wiki.collaborator_users.map(&:email).join(', ') %>
                        <%= f.submit "Save", class: 'btn btn-success' %>
                </div>
                <% end %>
                </div>
        </div>
  </div>

app/views/downgrade/new.html.erb
<h4>Would you like to downgrade your account back to standard?</h4>
<p>Remember, by doing so, all of your private wikis will become public.</p>
<%= link_to "Downgrade Your Account", downgrade_create_path, method: :create, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

		<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<div class="container">
			<ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
     

      <div class="pull-right-user-info">
        <% if user_signed_in? %>
          <div class="pull-right">
            <ul class="nav nav-tabs", style="border-bottom:1px;">
              <li class="username">Signed in as: <strong><%= current_user.email %></strong></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <% if current_user.standard? %>
              <li><%= link_to 'Upgrade to Premium', new_charge_path, :class => 'navbar-link' %></li>
            <% elsif current_user.premium? %>
              <li><%= link_to 'Downgrade Your Account', new_downgrade_path, :class => 'navbar-link' %></li>
            <% end %>  
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            </ul>
          </div>
        <% else %>
        <div class="pull-right">
          <ul class="nav nav-tabs", style="border-bottom:1px;">
            <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> </li>
            <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %><li>
          </ul>
        </div>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Blocipedia</h1>
<h4>Welcome to Blocipedia!</h4>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
<div class="form-group">
  <%= f.label :private, class: 'checkbox' do %>
    <%= f.check_box :private %> Private wiki
  <% end %>
</div>
<% end %>

app/views/wikis/edit.html.erb
<% if user_is_authorized_to_update? %>
  <h1> Edit Wiki </h1>

  <div class="row">
      <div class="col-md-4">
        <p> Guidelines for Wikis : </p>
        <ul>
          <li> Ensure your wiki is not a duplicate. </li>
          <li> Proofread! </li>
          <li> Fact check before posting. </li>
        </ul>
      </div>
      <div class="col-md-8">
        <%= form_for @wiki do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
          </div>
          <% if user_is_authorized_to_delete? %>
          <div class="form-group">
              <%= f.label :private, class: 'checkbox' do %>
                  <%= f.check_box :private %> Private wiki
              <% end %>
          <% end %>

          <div class="form-group">
              <%= f.label :body %>
              <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
          </div>
        
           <%= render template: 'collaborators/_form.html.erb'%>
      <%end%>
      
<% end %>

app/views/wikis/index.html.erb
<h1> Wikis </h1>
<div class="container">
  <div class="row">
      <div class="col-md-8">
        <% @wikis.each do |wiki| %>
          <div class="media">
            <div class="media-body">
              <h4 class="media-heading">
                <%= link_to wiki.title, wiki %>
              </h4>
              <small>
                <%= wiki.body %>
              </small>
            </div>
          </div>
        <% end %>
      </div>
      <% if user_is_authorized_to_create? %>
        <div class="row">
          <div class="pull-right">
            <%= link_to "Create new Wiki", new_wiki_path, class: 'btn btn-success' %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<% if user_is_authorized_to_create? %>
  <h1> New Wiki </h1>

  <div class="row">
      <div class="col-md-4">
        <p> Guidelines for Wikis : </p>
        <ul>
          <li> Ensure your wiki is not a duplicate. </li>
          <li> Proofread! </li>
          <li> Fact check before posting. </li>
        </ul>
      </div>
      <div class="col-md-8">
        <%= form_for @wiki do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
          </div>

        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
        <div class="form-group">
        <%= render partial: 'collaborators/form', locals: { f: f, collaborators: @wiki.collaborators } %>
        </div>

        <%= f.submit "Save", class: 'btn btn-success' %>
        <% end %>
      </div>
  </div>
<% end %>

app/views/wikis/show.html.erb
<div>
  <h1>
    <%= @wiki.title %> <br>
    <small>
      submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %>
    </small>
  </h1>

  <div class="row">
    <div class="col-md-8">
      <p><%= markdown(@wiki.body) %></p>
      <p><strong>Created by:</strong> <%= @wiki.user.email %></p>
     

         <% unless @wiki.collaborator_users.empty? %> 
          <p><strong>Collaborators:</strong><br>
              <%= show_collaborators %>
          <% end %></p>
    </div>
    
    <div class="col-md-4">
      <% if user_is_authorized_to_update? %>
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <% end %>
      <%if user_is_authorized_to_delete? %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
      <% end %>
    </div>
  </div>
</div>